import streamlit as st
import streamlit.components.v1 as components
from reflection_utils import render_reflection_form

_GAS_URL    = st.secrets["gas_url_probability_new"]
_SHEET_NAME = "승경도윤목"

_QUESTIONS = [
    {"type": "markdown", "text": "**📝 승경도·윤목으로 배우는 이산확률변수 성찰**"},
    {"key": "확률변수정의",  "label": "🎯 이 활동에서 정의한 확률변수 X는 무엇이고, 가능한 값의 범위는 얼마인지 설명하세요.",
     "type": "text_area", "height": 80},
    {"key": "기댓값의미",   "label": "💭 E(X)=6이 승경도 게임에서 어떤 의미인지, 자신의 말로 설명하세요.",
     "type": "text_area", "height": 80},
    {"key": "시뮬차이",     "label": "📊 시뮬레이션 결과가 이론값과 조금 다른 이유는 무엇이고, 시행 횟수를 늘리면 어떻게 될까요?",
     "type": "text_area", "height": 80},
    {"key": "분산의미",     "label": "📐 분산 V(X)=4, 표준편차 σ(X)=2는 게임에서 무엇을 의미하나요?",
     "type": "text_area", "height": 80},
    {"key": "새롭게알게된점", "label": "💡 새롭게 알게 된 점", "type": "text_area", "height": 90},
    {"key": "느낀점",        "label": "💬 느낀 점",           "type": "text_area", "height": 90},
]

META = {
    "title":       "미니: 승경도 윤목 시뮬레이션",
    "description": "조선시대 보드게임 승경도의 윤목으로 이산확률변수 X의 E(X)·V(X)를 탐구합니다.",
    "order":       1,
}

_HTML = (
    '<!doctype html><html><head><meta charset="utf-8">'
    '<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>'
    '<style>'
    '*{box-sizing:border-box;margin:0;padding:0}'
    'body{font-family:\'Segoe UI\',system-ui,sans-serif;background:linear-gradient(135deg,#0a1628 0%,#0f2027 50%,#0a1628 100%);padding:8px 10px;color:#e2e8f0}'
    '.card{background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.1);border-radius:18px;padding:14px 16px;margin:9px 0;backdrop-filter:blur(8px)}'
    '.card-title{font-size:16px;font-weight:700;color:#fbbf24;margin-bottom:10px;display:flex;align-items:center;gap:7px}'
    '.tab-nav{display:flex;gap:5px;margin-bottom:10px;flex-wrap:wrap}'
    '.tn{flex:1;min-width:70px;padding:8px 5px;border-radius:11px;border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.04);cursor:pointer;font-size:13px;font-weight:700;color:#94a3b8;transition:.2s;text-align:center}'
    '.tn:hover{background:rgba(251,191,36,.1);color:#fde68a}'
    '.tn.active{background:linear-gradient(135deg,rgba(180,83,9,.35),rgba(120,53,15,.25));color:#fbbf24;border-color:rgba(251,191,36,.5)}'
    '.tab-content{display:none}.tab-content.active{display:block}'
    '.hero{text-align:center;background:linear-gradient(135deg,rgba(180,120,30,.15),rgba(120,60,10,.08));border:2px solid rgba(251,191,36,.3);border-radius:20px;padding:14px 12px;margin-bottom:10px}'
    '.hero h1{font-size:23px;font-weight:900;color:#fbbf24;margin-bottom:4px}'
    '.hero .sub{font-size:13px;color:#94a3b8;line-height:1.5}'
    '.era-badge{display:inline-block;background:rgba(251,191,36,.15);border:1px solid rgba(251,191,36,.35);border-radius:20px;padding:2px 10px;font-size:12px;color:#fde68a;margin-bottom:7px;font-weight:600}'
    '.img-row{display:flex;gap:10px;align-items:flex-start;flex-wrap:wrap;margin:8px 0}'
    '.img-box{flex:0 0 auto;background:rgba(0,0,0,.2);border:1px solid rgba(255,255,255,.08);border-radius:12px;overflow:hidden;text-align:center}'
    '.img-box img{width:100%;height:auto;display:block}'
    '.img-caption{font-size:11px;color:#64748b;padding:4px 6px;font-style:italic;line-height:1.4}'
    '.info-box{flex:1;min-width:140px}'
    '.hgrid{display:grid;grid-template-columns:1fr 1fr;gap:8px}'
    '.hitem{background:rgba(255,255,255,.03);border:1px solid rgba(255,255,255,.07);border-radius:11px;padding:10px 11px}'
    '.hicon{font-size:24px;margin-bottom:4px}'
    '.htitle{font-size:13px;font-weight:700;color:#fbbf24;margin-bottom:3px}'
    '.htext{font-size:12px;color:#94a3b8;line-height:1.55}'
    '.yun-faces{display:flex;gap:6px;flex-wrap:wrap;margin:9px 0;justify-content:center}'
    '.face-card{background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.08);border-radius:11px;padding:9px 7px;text-align:center;min-width:64px;transition:.2s}'
    '.face-card:hover{background:rgba(251,191,36,.1);border-color:rgba(251,191,36,.3)}'
    '.fname{font-size:20px;font-weight:900;color:#fbbf24}'
    '.fdots{display:flex;justify-content:center;gap:3px;margin:4px 0;min-height:10px}'
    '.fdots .d{width:7px;height:7px;background:#fde68a;border-radius:50%;flex-shrink:0}'
    '.fval{font-size:12px;color:#cbd5e1;font-weight:600}'
    '.fprob{font-size:11px;color:#64748b;margin-top:1px}'
    '.throw-area{text-align:center;padding:6px 0}'
    '.throw-btn{background:linear-gradient(135deg,#b45309,#92400e);color:#fef3c7;border:none;border-radius:13px;padding:11px 30px;font-size:17px;font-weight:800;cursor:pointer;transition:all .18s;box-shadow:0 4px 12px rgba(180,83,9,.4)}'
    '.throw-btn:hover{background:linear-gradient(135deg,#d97706,#b45309);transform:translateY(-2px)}'
    '.throw-btn:disabled{opacity:.5;cursor:not-allowed;transform:none}'
    '.result-row{display:flex;gap:9px;justify-content:center;align-items:center;flex-wrap:wrap;margin:11px 0}'
    '.die-result{background:rgba(255,255,255,.05);border:2px solid rgba(255,255,255,.1);border-radius:13px;padding:11px 14px;text-align:center;min-width:88px;transition:.3s}'
    '.die-result.lit{background:rgba(251,191,36,.12);border-color:rgba(251,191,36,.5)}'
    '.dr-lbl{font-size:12px;color:#64748b;font-weight:600;margin-bottom:3px}'
    '.dr-name{font-size:29px;font-weight:900;color:#fbbf24}'
    '.dr-val{font-size:12px;color:#94a3b8}'
    '.sum-box{background:linear-gradient(135deg,rgba(99,102,241,.15),rgba(168,85,247,.1));border:2px solid rgba(99,102,241,.4);border-radius:13px;padding:11px 14px;text-align:center;min-width:88px;transition:.3s}'
    '.sum-box.lit{box-shadow:0 0 22px rgba(99,102,241,.3)}'
    '.sb-lbl{font-size:12px;color:#64748b;font-weight:600;margin-bottom:3px}'
    '.sb-val{font-size:38px;font-weight:900;color:#a5b4fc}'
    '.sb-sub{font-size:11px;color:#475569;margin-top:2px}'
    '.op{font-size:26px;color:#475569;font-weight:900}'
    '.log-wrap{max-height:60px;overflow-y:auto;display:flex;flex-wrap:wrap;gap:3px;padding:4px;margin-top:7px;background:rgba(255,255,255,.02);border-radius:9px}'
    '.lchip{background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.08);border-radius:6px;padding:2px 6px;font-size:12px;color:#cbd5e1;font-family:monospace}'
    '.lchip.new{background:rgba(251,191,36,.2);border-color:rgba(251,191,36,.4)}'
    'table{width:100%;border-collapse:collapse;font-size:13px;margin:7px 0}'
    'th{background:rgba(251,191,36,.14);color:#fbbf24;padding:6px 4px;text-align:center;border:1px solid rgba(255,255,255,.08);font-weight:700}'
    'td{background:rgba(255,255,255,.03);color:#e2e8f0;padding:5px 3px;text-align:center;border:1px solid rgba(255,255,255,.06);font-family:monospace}'
    'td.hi{background:rgba(99,102,241,.15)!important;color:#a5b4fc;font-weight:700}'
    '.calc-steps{display:flex;flex-direction:column;gap:6px;margin:8px 0}'
    '.step{background:rgba(255,255,255,.03);border-left:3px solid rgba(99,102,241,.5);border-radius:0 9px 9px 0;padding:8px 12px;font-size:13px;color:#cbd5e1;line-height:1.65;opacity:0;transform:translateX(-6px);transition:all .32s}'
    '.step.vis{opacity:1;transform:translateX(0)}'
    '.step .fml{font-family:monospace;color:#a5b4fc;display:block;margin:2px 0}'
    '.step .res{font-weight:700;color:#fbbf24}'
    '.stats-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:14px}'
    '.sbox{background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.1);border-radius:13px;padding:14px 10px;text-align:center;transition:.5s;min-width:0}'
    '.sbox.pop{background:rgba(251,191,36,.12);border-color:rgba(251,191,36,.4);}'
    '.slbl{font-size:11px;color:#64748b;font-weight:600;text-transform:uppercase;letter-spacing:.06em;margin-bottom:4px}'
    '.sval{font-size:26px;font-weight:900;color:#fbbf24;font-family:monospace}'
    '.sfml{font-size:11px;color:#475569;margin-top:3px}'
    '.reveal-btn{background:linear-gradient(135deg,rgba(99,102,241,.3),rgba(168,85,247,.2));border:1px solid rgba(99,102,241,.5);color:#a5b4fc;border-radius:11px;padding:7px 18px;font-size:14px;font-weight:700;cursor:pointer;transition:.2s;margin:4px 0}'
    '.reveal-btn:hover{background:linear-gradient(135deg,rgba(99,102,241,.45),rgba(168,85,247,.35))}'
    '.sim-ctrl{display:flex;align-items:center;gap:9px;flex-wrap:wrap;margin-bottom:9px}'
    '.nb{background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.12);color:#e2e8f0;border-radius:8px;padding:5px 12px;font-size:13px;font-weight:700;cursor:pointer;transition:.18s}'
    '.nb:hover,.nb.sel{background:rgba(251,191,36,.18);border-color:rgba(251,191,36,.4);color:#fbbf24}'
    '.sim-go{background:linear-gradient(135deg,#065f46,#047857);color:#d1fae5;border:none;border-radius:10px;padding:7px 18px;font-size:14px;font-weight:800;cursor:pointer;transition:.2s}'
    '.sim-go:hover{background:linear-gradient(135deg,#047857,#059669);transform:translateY(-1px)}'
    '.sim-go:disabled{opacity:.5;cursor:not-allowed;transform:none}'
    '.prog-bar{height:5px;background:rgba(255,255,255,.06);border-radius:3px;overflow:hidden;margin-bottom:9px}'
    '.prog-fill{height:100%;background:linear-gradient(90deg,#10b981,#06b6d4);border-radius:3px;transition:width .3s}'
    '.sim-res-row{display:flex;gap:7px;flex-wrap:wrap;margin:9px 0}'
    '.sr{flex:1;min-width:88px;background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.08);border-radius:10px;padding:8px 7px;text-align:center}'
    '.sr-lbl{font-size:11px;color:#64748b;font-weight:600;margin-bottom:3px}'
    '.sr-val{font-size:20px;font-weight:900;font-family:monospace}'
    '.sr-val.g{color:#34d399}.sr-val.y{color:#fbbf24}.sr-val.r{color:#f87171}'
    '.sr-th{font-size:11px;color:#475569;margin-top:2px}'
    '::-webkit-scrollbar{width:4px;height:4px}'
    '::-webkit-scrollbar-thumb{background:rgba(251,191,36,.4);border-radius:2px}'
    '</style></head><body>'

    # ── Tab Nav ──────────────────────────────────────────────────────────────
    '<div class="tab-nav">'
    '<button class="tn active" onclick="showTab(\'intro\')">🏛️ 승경도란?</button>'
    '<button class="tn" onclick="showTab(\'yun\')">🪵 윤목 던지기</button>'
    '<button class="tn" onclick="showTab(\'calc\')">📊 확률분포 &amp; 계산</button>'
    '<button class="tn" onclick="showTab(\'sim\')">🔬 시뮬레이션</button>'
    '</div>'

    # ── TAB 1 승경도 소개 ─────────────────────────────────────────────────────
    '<div id="tab-intro" class="tab-content active">'
    '<div class="hero">'
    '<div class="era-badge">🏛️ 조선시대 전통 보드게임</div>'
    '<h1>승경도(陞卿圖) 놀이</h1>'
    '<p class="sub">관직에 오르는 꿈을 키우는 조선의 보드게임. 이산확률변수와 기댓값을 탐구해 봅시다</p>'
    '</div>'
    '<div class="card">'
    '<div class="card-title">🖼️ 승경도 게임판</div>'
    '<div class="img-row">'
    '<div class="img-box" style="width:240px">'
    '<img src="##BOARD_IMG##" alt="승경도 게임판" style="width:100%;height:auto;border-radius:12px 12px 0 0">'
    '<div class="img-caption">실제 승경도(陞卿圖) 게임판 — 관직명이 빼곡히 적힌 종이판</div>'
    '</div>'
    '<div class="info-box">'
    '<div class="hgrid">'
    '<div class="hitem"><div class="hicon">📜</div><div class="htitle">역사적 배경</div><div class="htext">조선시대 양반가 자제들이 <b style="color:#fde68a">복잡한 관직 체계</b>를 놀이로 익히며 관직에 오르는 꿈을 키우는 교육용 보드게임입니다.</div></div>'
    '<div class="hitem"><div class="hicon">✍️</div><div class="htitle">창안자</div><div class="htext"><b style="color:#fde68a">하륜</b>이 창안했다는 기록이 《용재총화》에 전합니다. 종경도·승정도라고도 불립니다.</div></div>'
    '<div class="hitem"><div class="hicon">📋</div><div class="htitle">게임판 구성</div><div class="htext">폭 1m×길이 1.5m 종이에 <b style="color:#fde68a">300여 개 칸</b>이 있고 각 칸에 관직명이 적혀 있습니다.</div></div>'
    '<div class="hitem"><div class="hicon">🏆</div><div class="htitle">승리 조건</div><div class="htext"><b style="color:#fde68a">영의정·봉조하</b>(문과)나 <b style="color:#fde68a">도원수</b>(무과)에 먼저 도달해 퇴직하면 이깁니다.</div></div>'
    '</div>'
    '</div>'
    '</div>'
    '</div>'
    '<div class="card">'
    '<div class="card-title">📌 이 활동의 수학적 탐구</div>'
    '<p style="font-size:13px;color:#94a3b8;line-height:1.75">'
    '승경도에서는 <b style="color:#fde68a">윤목</b>(특수 주사위)을 던져 나온 눈금만큼 이동합니다.<br>'
    '이 활동의 <b style="color:#a5b4fc">확률변수 X</b>:'
    '</p>'
    '<div style="margin:10px 0;background:rgba(251,191,36,.08);border:1px solid rgba(251,191,36,.3);border-radius:10px;padding:10px 14px;font-family:monospace;font-size:14px;color:#fde68a;text-align:center">'
    'X = 윤목을 두 번 던져서 나오는 눈금의 수의 합'
    '</div>'
    '<p style="font-size:13px;color:#94a3b8">X의 가능한 값: <b style="color:#fde68a">2, 3, 4, 5, 6, 7, 8, 9, 10</b>  탭을 순서대로 탐구하며 E(X)와 V(X)를 구해 보세요!</p>'
    '</div>'
    '</div>'

    # ── TAB 2 윤목 던지기 ─────────────────────────────────────────────────────
    '<div id="tab-yun" class="tab-content">'
    '<div class="card">'
    '<div class="card-title">🪵 윤목(輪木)이란?</div>'
    '<div class="img-row">'
    '<div class="img-box" style="width:280px">'
    '<img src="##YUNMOK_IMG##" alt="윤목" style="width:100%;height:auto;border-radius:12px 12px 0 0">'
    '<div class="img-caption">윤목(輪木) — 5면으로 깎은 승경도 전용 주사위</div>'
    '</div>'
    '<div class="info-box" style="font-size:13px;color:#94a3b8;line-height:1.75">'
    '<p><b style="color:#fde68a">윤목</b>은 한 뼘 길이, 두께 약 3cm의 나무를 <b style="color:#fde68a">5면</b>으로 깎아 만든 승경도 전용 주사위입니다.</p>'
    '<p style="margin-top:7px">던지면 한 모서리가 위로 올라와 그 눈금을 읽습니다. 각 눈금이 나올 확률은 모두 <b style="color:#a5b4fc">1/5</b>로 같습니다.</p>'
    '<p style="margin-top:7px"><b style="color:#fde68a">윤목은 한국 고유의 주사위</b>로, 중국 승관도에는 없는 특징입니다.</p>'
    '</div>'
    '</div>'
    '</div>'
    '<div class="card">'
    '<div class="card-title">🎲 윤목의 5개 면</div>'
    '<div class="yun-faces" id="facesWrap"></div>'
    '<p style="font-size:12px;color:#475569;text-align:center;margin-top:4px">각 눈금 확률: P = <span style="color:#fbbf24;font-weight:700">1/5</span> = 0.2</p>'
    '</div>'
    '<div class="card">'
    '<div class="card-title">🎯 윤목 두 번 던지기</div>'
    '<p style="font-size:13px;color:#94a3b8;margin-bottom:9px">버튼을 눌러 윤목을 두 번 던지고, 합 X를 관찰하세요.</p>'
    '<div class="throw-area">'
    '<button class="throw-btn" id="throwBtn" onclick="throwDice()">🎲 윤목 던지기!</button>'
    '<div class="result-row">'
    '<div class="die-result" id="d1"><div class="dr-lbl">1번째 윤목</div><div class="dr-name" id="d1n">—</div><div class="dr-val" id="d1v"></div></div>'
    '<div class="op">+</div>'
    '<div class="die-result" id="d2"><div class="dr-lbl">2번째 윤목</div><div class="dr-name" id="d2n">—</div><div class="dr-val" id="d2v"></div></div>'
    '<div class="op">=</div>'
    '<div class="sum-box" id="sumBox"><div class="sb-lbl">X (합)</div><div class="sb-val" id="sumV">—</div><div class="sb-sub" id="sumS"></div></div>'
    '</div>'
    '<div class="log-wrap" id="histLog"><span style="color:#475569;font-size:12px">아직 기록이 없습니다.</span></div>'
    '</div>'
    '</div>'
    '</div>'

    # ── TAB 3 확률분포 & 계산 ────────────────────────────────────────────────
    '<div id="tab-calc" class="tab-content">'
    '<div class="card">'
    '<div class="card-title">📊 확률변수 X의 확률분포표</div>'
    '<p style="font-size:13px;color:#94a3b8;margin-bottom:7px">전체 경우의 수: <b style="color:#fde68a">5×5 = 25</b>가지</p>'
    '<div style="overflow-x:auto"><table id="distTable"></table></div>'
    '<canvas id="distChart" height="120" style="margin-top:10px"></canvas>'
    '</div>'
    '<div class="card">'
    '<div class="card-title">🔢 E(X)와 V(X) 구하기</div>'
    '<button class="reveal-btn" id="revBtn" onclick="revealSteps()">📐 단계별 계산 보기</button>'
    '<div class="calc-steps" id="calcSteps"></div>'
    '<div class="stats-grid">'
    '<div class="sbox" id="sb0"><div class="slbl">기댓값 E(X)</div><div class="sval" id="sv0">?</div><div class="sfml">Σ x·P(X=x)</div></div>'
    '<div class="sbox" id="sb1"><div class="slbl">분산 V(X)</div><div class="sval" id="sv1">?</div><div class="sfml">E(X²)−[E(X)]²</div></div>'
    '<div class="sbox" id="sb2"><div class="slbl">표준편차 σ(X)</div><div class="sval" id="sv2">?</div><div class="sfml">√V(X)</div></div>'
    '</div>'
    '</div>'
    '</div>'

    # ── TAB 4 시뮬레이션 ─────────────────────────────────────────────────────
    '<div id="tab-sim" class="tab-content">'
    '<div class="card">'
    '<div class="card-title">🔬 몬테카를로 시뮬레이션</div>'
    '<p style="font-size:13px;color:#94a3b8;margin-bottom:9px;line-height:1.6">'
    '많은 횟수를 시뮬레이션하면 표본평균·분산이 이론값(<b>E(X)=6, V(X)=4</b>)에 가까워지는지 확인해 봅시다.'
    '</p>'
    '<div class="sim-ctrl">'
    '<div style="display:flex;gap:5px;flex-wrap:wrap" id="nBtns"></div>'
    '<button class="sim-go" id="simGoBtn" onclick="runSim()">▶ 실행</button>'
    '</div>'
    '<div class="prog-bar"><div class="prog-fill" id="progFill" style="width:0"></div></div>'
    '<div class="sim-res-row" id="simResRow"></div>'
    '</div>'
    '<div class="card" id="simChartCard" style="display:none">'
    '<div class="card-title">📈 시뮬레이션 vs 이론값 비교</div>'
    '<canvas id="simChart" height="150"></canvas>'
    '<p style="font-size:11px;color:#475569;text-align:center;margin-top:5px">초록 막대: 시뮬레이션 비율 &nbsp;|&nbsp; 노란 선: 이론 확률</p>'
    '</div>'
    '</div>'

    # ── JavaScript ───────────────────────────────────────────────────────────
    '<script>'
    'const FACES=[{name:"도",val:1},{name:"개",val:2},{name:"걸",val:3},{name:"윷",val:4},{name:"모",val:5}];'
    'const DIST=[];for(let x=2;x<=10;x++)DIST.push({x,cnt:5-Math.abs(x-6)});'
    'function showTab(id){'
    '  document.querySelectorAll(".tab-content").forEach(t=>t.classList.remove("active"));'
    '  document.querySelectorAll(".tn").forEach(b=>b.classList.remove("active"));'
    '  document.getElementById("tab-"+id).classList.add("active");'
    '  const idx={intro:0,yun:1,calc:2,sim:3}[id];'
    '  document.querySelectorAll(".tn")[idx].classList.add("active");'
    '  if(id==="calc"&&!distChartBuilt)buildDistChart();'
    '}'
    'function buildFaces(){'
    '  document.getElementById("facesWrap").innerHTML=FACES.map(f=>{'
    '    const dots=Array(f.val).fill(\'<span class="d"></span>\').join("");'
    '    return `<div class="face-card"><div class="fname">${f.name}</div><div class="fdots">${dots}</div><div class="fval">눈금 ${f.val}</div><div class="fprob">P=1/5</div></div>`;'
    '  }).join("");'
    '}'
    'function buildDistTable(){'
    '  let h="<thead><tr><th>X</th>";'
    '  DIST.forEach(d=>h+=`<th>${d.x}</th>`);'
    '  h+="<th>합계</th></tr></thead><tbody>";'
    '  let r1="<tr><td>경우의 수</td>";'
    '  DIST.forEach(d=>r1+=`<td>${d.cnt}</td>`);r1+=\'<td class="hi">25</td></tr>\';'
    '  let r2="<tr><td>P(X=x)</td>";'
    '  DIST.forEach(d=>r2+=`<td>${d.cnt}/25</td>`);r2+=\'<td class="hi">1</td></tr>\';'
    '  document.getElementById("distTable").innerHTML=h+r1+r2+"</tbody>";'
    '}'
    'let distChartBuilt=false,distCO=null;'
    'function buildDistChart(){'
    '  if(distChartBuilt)return;distChartBuilt=true;'
    '  const ctx=document.getElementById("distChart").getContext("2d");'
    '  distCO=new Chart(ctx,{type:"bar",'
    '    data:{labels:DIST.map(d=>`X=${d.x}`),datasets:[{label:"P(X=x)",data:DIST.map(d=>d.cnt/25),'
    '      backgroundColor:DIST.map(d=>d.x===6?"rgba(251,191,36,.7)":"rgba(99,102,241,.5)"),'
    '      borderColor:DIST.map(d=>d.x===6?"rgba(251,191,36,1)":"rgba(99,102,241,.8)"),'
    '      borderWidth:2,borderRadius:4}]},'
    '    options:{responsive:true,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>`P=${(c.raw*25).toFixed(0)}/25`}}},'
    '      scales:{x:{ticks:{color:"#94a3b8",font:{size:12}},grid:{color:"rgba(255,255,255,.05)"}},'
    '              y:{ticks:{color:"#94a3b8",font:{size:11},callback:v=>`${(v*100).toFixed(0)}%`},grid:{color:"rgba(255,255,255,.05)"},max:0.22}}}});'
    '}'
    'const STEPS=['
    '  {t:"① X의 범위",b:"최솟값=1+1=2, 최댓값=5+5=10. 전체 경우의 수: 5×5=25",f:"X∈{2,3,...,10}"},'
    '  {t:"② E(X) = Σ x·P(X=x)",b:"분자: 2×1+3×2+4×3+5×4+6×5+7×4+8×3+9×2+10×1",f:"=(2+6+12+20+30+28+24+18+10)/25=<span class=\'res\'>150/25=6</span>"},'
    '  {t:"③ E(X²) = Σ x²·P(X=x)",b:"분자: 4×1+9×2+16×3+25×4+36×5+49×4+64×3+81×2+100×1",f:"=(4+18+48+100+180+196+192+162+100)/25=<span class=\'res\'>1000/25=40</span>"},'
    '  {t:"④ V(X) = E(X²)−[E(X)]²",b:"분산 공식 적용",f:"=40−6²=40−36=<span class=\'res\'>4</span>"},'
    '  {t:"⑤ σ(X) = √V(X)",b:"표준편차 계산",f:"=√4=<span class=\'res\'>2</span>"},'
    '  {t:"⑥ 해석",b:"윤목을 두 번 던지면 평균 합은 6이고, 표준편차는 2입니다.",f:"<span class=\'res\'>E(X)=6, V(X)=4, σ(X)=2</span>"},'
    '];'
    'let stepsShown=false;'
    'function revealSteps(){'
    '  if(stepsShown)return;stepsShown=true;'
    '  document.getElementById("revBtn").style.display="none";'
    '  const w=document.getElementById("calcSteps");'
    '  w.innerHTML=STEPS.map((s,i)=>`<div class="step" id="st${i}"><strong style="color:#fbbf24">${s.t}</strong><br><span style="color:#94a3b8">${s.b}</span><span class="fml">${s.f}</span></div>`).join("");'
    '  STEPS.forEach((_,i)=>setTimeout(()=>document.getElementById("st"+i)?.classList.add("vis"),i*280));'
    '  [["sv0","6"],["sv1","4"],["sv2","2"]].forEach(([id,v],i)=>setTimeout(()=>{document.getElementById(id).textContent=v;document.getElementById("sb"+i).classList.add("pop");},STEPS.length*280+i*160));'
    '  if(!distChartBuilt)buildDistChart();'
    '}'
    'let rolling=false;const LOGS=[];'
    'function throwDice(){'
    '  if(rolling)return;rolling=true;'
    '  document.getElementById("throwBtn").disabled=true;'
    '  const d1=document.getElementById("d1"),d2=document.getElementById("d2"),sb=document.getElementById("sumBox");'
    '  d1.classList.remove("lit");d2.classList.remove("lit");sb.classList.remove("lit");'
    '  let t=0;'
    '  const iv=setInterval(()=>{'
    '    const f1=FACES[Math.floor(Math.random()*5)],f2=FACES[Math.floor(Math.random()*5)];'
    '    document.getElementById("d1n").textContent=f1.name;'
    '    document.getElementById("d2n").textContent=f2.name;'
    '    document.getElementById("sumV").textContent=f1.val+f2.val;'
    '    t+=60;if(t>640){'
    '      clearInterval(iv);'
    '      const r1=FACES[Math.floor(Math.random()*5)],r2=FACES[Math.floor(Math.random()*5)];'
    '      const sum=r1.val+r2.val;'
    '      document.getElementById("d1n").textContent=r1.name;'
    '      document.getElementById("d1v").textContent=`눈금 ${r1.val}`;'
    '      document.getElementById("d2n").textContent=r2.name;'
    '      document.getElementById("d2v").textContent=`눈금 ${r2.val}`;'
    '      document.getElementById("sumV").textContent=sum;'
    '      document.getElementById("sumS").textContent=`(${r1.name}+${r2.name})`;'
    '      d1.classList.add("lit");d2.classList.add("lit");sb.classList.add("lit");'
    '      LOGS.unshift(`${r1.name}+${r2.name}=${sum}`);'
    '      if(LOGS.length>24)LOGS.pop();'
    '      document.getElementById("histLog").innerHTML=LOGS.map((l,i)=>`<span class="lchip${i===0?" new":""}">${l}</span>`).join("");'
    '      rolling=false;document.getElementById("throwBtn").disabled=false;'
    '    }'
    '  },60);'
    '}'
    'let simN=500,simCO=null;const SIM_NS=[100,500,1000,5000,10000];'
    'function buildSimCtrl(){'
    '  document.getElementById("nBtns").innerHTML=SIM_NS.map(n=>`<button class="nb${n===simN?" sel":""}" onclick="setN(${n})">${n.toLocaleString()}회</button>`).join("");'
    '}'
    'function setN(n){simN=n;buildSimCtrl();}'
    'function runSim(){'
    '  document.getElementById("simGoBtn").disabled=true;'
    '  document.getElementById("progFill").style.width="0";'
    '  const res=[],total=simN;let done=0;'
    '  function batch(){'
    '    const chunk=Math.min(500,total-done);'
    '    for(let i=0;i<chunk;i++)res.push(FACES[Math.floor(Math.random()*5)].val+FACES[Math.floor(Math.random()*5)].val);'
    '    done+=chunk;'
    '    document.getElementById("progFill").style.width=`${(done/total*100).toFixed(0)}%`;'
    '    if(done<total)requestAnimationFrame(batch);else showSim(res);'
    '  }'
    '  requestAnimationFrame(batch);'
    '}'
    'function showSim(res){'
    '  const n=res.length,mean=res.reduce((a,b)=>a+b,0)/n;'
    '  const ex2=res.reduce((a,b)=>a+b*b,0)/n,vari=ex2-mean*mean,std=Math.sqrt(vari);'
    '  const cc=(v,t,tol)=>Math.abs(v-t)<=tol*0.5?"g":Math.abs(v-t)<=tol*1.5?"y":"r";'
    '  document.getElementById("simResRow").innerHTML=['
    '    {lbl:"표본 평균",val:mean.toFixed(3),th:6,tol:0.3},'
    '    {lbl:"표본 분산",val:vari.toFixed(3),th:4,tol:0.5},'
    '    {lbl:"표본 표준편차",val:std.toFixed(3),th:2,tol:0.3},'
    '  ].map(m=>`<div class="sr"><div class="sr-lbl">${m.lbl}</div><div class="sr-val ${cc(parseFloat(m.val),m.th,m.tol)}">${m.val}</div><div class="sr-th">이론: ${m.th}</div></div>`).join("");'
    '  const freq=Array(9).fill(0);res.forEach(v=>freq[v-2]++);'
    '  document.getElementById("simChartCard").style.display="block";'
    '  if(simCO)simCO.destroy();'
    '  simCO=new Chart(document.getElementById("simChart").getContext("2d"),{type:"bar",'
    '    data:{labels:DIST.map(d=>`X=${d.x}`),datasets:['
    '      {label:"시뮬 비율",data:freq.map(f=>f/n),backgroundColor:"rgba(52,211,153,.45)",borderColor:"rgba(52,211,153,.8)",borderWidth:2,borderRadius:4},'
    '      {label:"이론 확률",data:DIST.map(d=>d.cnt/25),type:"line",borderColor:"#fbbf24",borderWidth:2.5,pointBackgroundColor:"#fbbf24",pointRadius:4,tension:.4,fill:false}'
    '    ]},'
    '    options:{responsive:true,plugins:{legend:{labels:{color:"#94a3b8",font:{size:12}}}},'
    '      scales:{x:{ticks:{color:"#94a3b8",font:{size:12}},grid:{color:"rgba(255,255,255,.04)"}},'
    '              y:{ticks:{color:"#94a3b8",font:{size:11},callback:v=>`${(v*100).toFixed(1)}%`},grid:{color:"rgba(255,255,255,.04)"},max:0.24}}}});'
    '  document.getElementById("simGoBtn").disabled=false;'
    '}'

    'buildFaces();buildDistTable();buildSimCtrl();'
    '</script></body></html>'
)


def _load_img_b64(rel_path: str) -> str:
    import base64, os
    abs_path = os.path.join(os.path.dirname(__file__), "..", "..", "..", "assets", rel_path)
    abs_path = os.path.normpath(abs_path)
    if not os.path.exists(abs_path):
        return ""
    with open(abs_path, "rb") as f:
        data = base64.b64encode(f.read()).decode()
    ext = os.path.splitext(abs_path)[1].lower().lstrip(".")
    mime = {"png": "image/png", "jpg": "image/jpeg", "jpeg": "image/jpeg"}.get(ext, "image/png")
    return f"data:{mime};base64,{data}"


def render():
    st.header("🎲 승경도 윤목 — 이산확률변수의 기댓값과 분산")
    st.markdown(
        "조선시대 전통 보드게임 **승경도**의 윤목으로 "
        "확률변수 $X$의 **기댓값** $E(X)$와 **분산** $V(X)$를 탐구합니다. "
        "아래 탭을 순서대로 살펴보세요!"
    )
    board_uri  = _load_img_b64("probability_new/seunggyeongdo_board.png")
    yunmok_uri = _load_img_b64("probability_new/yunmok.png")
    html = _HTML.replace("##BOARD_IMG##", board_uri).replace("##YUNMOK_IMG##", yunmok_uri)
    components.html(html, height=1600, scrolling=True)
    render_reflection_form(_SHEET_NAME, _GAS_URL, _QUESTIONS)
